# Generated by Django 5.0 on 2025-01-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('conposition', models.TextField()),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('MF', 'Muffins'), ('CK', 'Cookies'), ('VW', 'Veggie Wraps'), ('FR', 'Fries'), ('GB', 'Garlic Bread'), ('GS', 'Grilled Cheese Sandwiches'), ('MH', 'Mocha'), ('MC', 'Masala Chai')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
