# Generated by Django 5.0 on 2025-01-29 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='conposition',
            new_name='composition',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DR', 'Drinks'), ('MM', 'Momos'), ('SC', 'Snacks'), ('DS', 'Desserts'), ('MF', 'Muffins'), ('CK', 'Cookies'), ('VW', 'Veggie Wraps'), ('FR', 'Fries'), ('GB', 'Garlic Bread'), ('GS', 'Sandwiches'), ('MH', 'Mocha'), ('MC', 'Masala Chai')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Nagpur', 'Nagpur'), ('Nashik', 'Nashik'), ('Thane', 'Thane'), ('Aurangabad', 'Aurangabad'), ('Solapur', 'Solapur'), ('Amravati', 'Amravati'), ('Kolhapur', 'Kolhapur'), ('Navi Mumbai', 'Navi Mumbai'), ('Kalyan-Dombivli', 'Kalyan-Dombivli'), ('Vasai-Virar', 'Vasai-Virar'), ('Mira-Bhayandar', 'Mira-Bhayandar'), ('Bhiwandi', 'Bhiwandi'), ('Malegaon', 'Malegaon'), ('Jalgaon', 'Jalgaon'), ('Akola', 'Akola'), ('Latur', 'Latur'), ('Dhule', 'Dhule'), ('Ahmednagar', 'Ahmednagar'), ('Chandrapur', 'Chandrapur'), ('Parbhani', 'Parbhani'), ('Ichalkaranji', 'Ichalkaranji'), ('Sangli', 'Sangli'), ('Jalna', 'Jalna'), ('Nanded', 'Nanded'), ('Ratnagiri', 'Ratnagiri'), ('Beed', 'Beed'), ('Yavatmal', 'Yavatmal'), ('Osmanabad', 'Osmanabad'), ('Satara', 'Satara'), ('Wardha', 'Wardha'), ('Gondia', 'Gondia'), ('Baramati', 'Baramati'), ('Hingoli', 'Hingoli'), ('Buldhana', 'Buldhana'), ('Washim', 'Washim')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
