# Generated by Django 5.0 on 2025-01-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_conposition_product_composition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Nagpur', 'Nagpur'), ('Nashik', 'Nashik'), ('Thane', 'Thane'), ('Aurangabad', 'Aurangabad'), ('Solapur', 'Solapur'), ('Amravati', 'Amravati'), ('Kolhapur', 'Kolhapur'), ('Navi Mumbai', 'Navi Mumbai'), ('Kalyan-Dombivli', 'Kalyan-Dombivli'), ('Vasai-Virar', 'Vasai-Virar'), ('Mira-Bhayandar', 'Mira-Bhayandar'), ('Bhiwandi', 'Bhiwandi'), ('Malegaon', 'Malegaon'), ('Jalgaon', 'Jalgaon'), ('Akola', 'Akola'), ('Latur', 'Latur'), ('Dhule', 'Dhule'), ('Ahmednagar', 'Ahmednagar'), ('Chandrapur', 'Chandrapur'), ('Parbhani', 'Parbhani'), ('Ichalkaranji', 'Ichalkaranji'), ('Sangli', 'Sangli'), ('Jalna', 'Jalna'), ('Nanded', 'Nanded'), ('Ratnagiri', 'Ratnagiri'), ('Beed', 'Beed'), ('Yavatmal', 'Yavatmal'), ('Osmanabad', 'Osmanabad'), ('Satara', 'Satara'), ('Wardha', 'Wardha'), ('Gondia', 'Gondia'), ('Baramati', 'Baramati'), ('Hingoli', 'Hingoli'), ('Buldhana', 'Buldhana'), ('Washim', 'Washim')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
